"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Camera, Check, Store } from "lucide-react";
import { ChangeEvent, FormEvent, useState } from "react";
import { defaultCheckoutConfig } from "@/lib/mock-data";
import { countryOptions, currencyOptions } from "@/lib/settings";
import { routes } from "@/lib/routes";
import { storageKeys, writeStorage } from "@/lib/storage";
import {
  clearSupabaseBrowserSession,
  createSupabaseBrowserClient,
  isInvalidRefreshTokenError,
} from "@/lib/supabase/client";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import {
  createOrUpdateStoreFromOnboarding,
  uploadImage,
} from "@/lib/supabase/data";
import type { CountryCode, CurrencyCode, StoreSettings } from "@/lib/types";

const fieldClass="h-12 w-full rounded-lg border border-[#c7c4d8] bg-white px-4 text-[14px] outline-none transition-all focus:border-[#3525cd] focus:ring-2 focus:ring-[#3525cd]/20";

export function OnboardingPage(){
  const router=useRouter();const [step,setStep]=useState(1);const [logo,setLogo]=useState("");const [logoFile,setLogoFile]=useState<File|null>(null);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);
  const [identity,setIdentity]=useState({storeName:"",country:"US" as CountryCode,category:"",phone:"",email:""});
  const [currency,setCurrency]=useState<CurrencyCode>("USD");const [checkout,setCheckout]=useState({requirePhone:true,requireAddress:true,trackingEnabled:true});
  const upload=(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];if(!file)return;setLogoFile(file);const reader=new FileReader();reader.onload=()=>setLogo(String(reader.result));reader.readAsDataURL(file)};
  const next=(event:FormEvent)=>{event.preventDefault();if(step<3)setStep(value=>value+1);else finish()};
  const finish=async()=>{setSaving(true);setMessage("");try{const country=countryOptions.find(option=>option.code===identity.country)||countryOptions.find(option=>option.code==="US")!;let logoUrl=logo;const settings:StoreSettings={storeName:identity.storeName.trim()||"New Store",businessPhone:identity.phone.trim(),businessEmail:identity.email.trim(),country:identity.country,currency,timezone:country.timezone,phoneFormat:country.phone,dateFormat:identity.country==="US"?"MM/DD/YYYY":"DD/MM/YYYY",logo};if(isSupabaseConfigured()){const supabase=createSupabaseBrowserClient();const {data:{user},error:userError}=await supabase.auth.getUser();if(userError&&isInvalidRefreshTokenError(userError)){await clearSupabaseBrowserSession(supabase);throw new Error("Your session expired. Please log in again before completing setup.")}if(userError)throw userError;if(!user)throw new Error("Please log in again before completing setup.");if(logoFile)logoUrl=await uploadImage(supabase,"store-logos",user.id,logoFile);await createOrUpdateStoreFromOnboarding(supabase,{storeName:settings.storeName,country:settings.country,currency:settings.currency,timezone:settings.timezone,phoneFormat:settings.phoneFormat,dateFormat:settings.dateFormat,businessPhone:settings.businessPhone,businessEmail:settings.businessEmail,category:identity.category,logoUrl,requirePhone:checkout.requirePhone,requireAddress:checkout.requireAddress,trackingEnabled:checkout.trackingEnabled});}writeStorage(storageKeys.settings,{...settings,logo:logoUrl});writeStorage(storageKeys.checkout,{...defaultCheckoutConfig,storeName:settings.storeName||defaultCheckoutConfig.storeName,logo:logoUrl,requirePhone:checkout.requirePhone,requireAddress:checkout.requireAddress,trackingEnabled:checkout.trackingEnabled});writeStorage(storageKeys.onboarding,{completed:true,category:identity.category,currency,completedAt:new Date().toISOString()});router.push(routes.dashboard);router.refresh()}catch(error){setMessage(error instanceof Error?error.message:"Could not complete onboarding.")}finally{setSaving(false)}};
  const skip=()=>{if(step===2)return;if(step===1){setIdentity(value=>({...value,storeName:"",category:"",phone:"",email:""}));setLogo("");setStep(2)}else finish()};
  return <div className="relative min-h-screen bg-[#f9f9ff] px-5 py-20 text-[#141b2b]"><Link href={routes.home} className="absolute left-5 top-6 flex items-center gap-2 text-[13px] font-medium text-[#646273] hover:text-[#3525cd]"><ArrowLeft size={15}/>Back to home</Link><main className="mx-auto w-full max-w-[620px]"><header className="mb-8 text-center"><Link href={routes.home} className="text-[25px] font-bold text-[#3525cd]">OrderFlow</Link><p className="mt-2 text-[15px] text-[#646273]">Set up the essentials now. You can complete optional details later.</p></header><section className="mb-5"><div className="mb-3 flex justify-between text-[13px]"><b className="text-[#3525cd]">Step {step} of 3</b><span className="text-[#646273]">{Math.round(step/3*100)}% complete</span></div><div className="h-2 overflow-hidden rounded-full bg-[#dce2f7]"><div className="h-full bg-[#3525cd] transition-all" style={{width:`${step/3*100}%`}}/></div><div className="mt-4 grid grid-cols-3 text-center text-[12px] font-semibold text-[#646273]">{["Store Identity","Currency Setup","Checkout Basics"].map((label,index)=><span key={label} className={step===index+1?"text-[#3525cd]":""}>{index+1}. {label}</span>)}</div></section><form onSubmit={next} className="rounded-2xl border border-[#dedde8] bg-white p-6 shadow-[0_14px_45px_rgba(20,27,43,.07)] sm:p-10">
    {step===1&&<><div className="mb-7"><span className="mb-3 grid h-11 w-11 place-items-center rounded-xl bg-[#eeedff] text-[#3525cd]"><Store size={21}/></span><h1 className="text-[25px] font-semibold tracking-[-.02em]">Store identity</h1><p className="mt-2 text-[14px] leading-6 text-[#646273]">These details are optional. A store name is required before creating products or checkout links.</p></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Store Name"><input className={fieldClass} value={identity.storeName} onChange={e=>setIdentity(v=>({...v,storeName:e.target.value}))} placeholder="Your store name"/></Field><Field label="Country"><select className={fieldClass} value={identity.country} onChange={e=>setIdentity(v=>({...v,country:e.target.value as CountryCode}))}>{countryOptions.map(option=><option key={option.code} value={option.code}>{option.label}</option>)}</select></Field><Field label="Store Category"><select className={fieldClass} value={identity.category} onChange={e=>setIdentity(v=>({...v,category:e.target.value}))}><option value="">Select category</option><option>Fashion &amp; Apparel</option><option>Beauty</option><option>Food</option><option>Home &amp; Lifestyle</option><option>Other</option></select></Field><Field label="Business Phone"><input className={fieldClass} value={identity.phone} onChange={e=>setIdentity(v=>({...v,phone:e.target.value}))} placeholder="Optional"/></Field><Field label="Business Email"><input type="email" className={fieldClass} value={identity.email} onChange={e=>setIdentity(v=>({...v,email:e.target.value}))} placeholder="Optional"/></Field><Field label="Store Logo"><label className="relative flex h-12 cursor-pointer items-center gap-3 rounded-lg border border-dashed border-[#c7c4d8] px-4 text-[13px]"><Camera size={18} className="text-[#3525cd]"/>{logo?"Logo selected":"Upload logo (optional)"}<input className="absolute inset-0 opacity-0" type="file" accept="image/*" onChange={upload}/></label></Field></div></>}
    {step===2&&<><div className="mb-7"><h1 className="text-[25px] font-semibold tracking-[-.02em]">Choose your currency</h1><p className="mt-2 text-[14px] leading-6 text-[#646273]">Currency is required and cannot be changed later because historic prices are not converted.</p></div><Field label="Store Currency (required)"><select required className={fieldClass} value={currency} onChange={e=>setCurrency(e.target.value as CurrencyCode)}>{currencyOptions.map(code=><option key={code}>{code}</option>)}</select></Field><div className="mt-5 rounded-xl bg-[#f1f3ff] p-4 text-[13px] leading-6 text-[#464555]"><b className="block text-[#141b2b]">Default: USD</b>Confirm this selection before continuing. You can still change country, timezone, and formatting later.</div></>}
    {step===3&&<><div className="mb-7"><h1 className="text-[25px] font-semibold tracking-[-.02em]">Checkout basics</h1><p className="mt-2 text-[14px] leading-6 text-[#646273]">Set sensible defaults for your customer checkout. These options remain editable.</p></div><div className="grid gap-3">{[["Phone number required","requirePhone"],["Address required","requireAddress"],["Order tracking enabled","trackingEnabled"]].map(([label,key])=><label key={key} className="flex min-h-14 items-center justify-between rounded-xl border border-[#e5e7eb] px-4 text-[14px] font-semibold"><span>{label}</span><input type="checkbox" className="h-5 w-5 accent-[#3525cd]" checked={checkout[key as keyof typeof checkout]} onChange={e=>setCheckout(v=>({...v,[key]:e.target.checked}))}/></label>)}</div></>}
    {message&&<p role="alert" className="auth-form-error mt-5">{message}</p>}<div className="mt-9 flex flex-wrap items-center justify-between gap-3"><button type="button" className="btn-secondary" onClick={()=>step>1?setStep(value=>value-1):router.push(routes.signup)}><ArrowLeft size={15}/>Back</button><div className="ml-auto flex gap-2">{step!==2&&<button type="button" className="btn-secondary" onClick={skip}>Skip for now</button>}<button className="btn-primary min-w-32" disabled={saving}>{saving?"Saving...":step===3?"Finish setup":"Continue"}{step<3?<ArrowRight size={15}/>:<Check size={15}/>}</button></div></div>
  </form></main></div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-2 block text-[13px] font-semibold">{label}</span>{children}</label>}
