"use client";

import { useRouter } from "next/navigation";
import { BarChart3, Boxes, CheckCircle2, Download, MapPin, Repeat2, ShoppingBag, TrendingUp, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { calculateAnalytics, type AnalyticsRange } from "@/lib/analytics";
import { downloadCsv } from "@/lib/csv";
import { routes } from "@/lib/routes";
import type { Product } from "@/lib/types";
import { DashboardShell } from "./dashboard-shell";
import { useDashboard } from "./dashboard-store";
import { EmptyState, StatCard } from "./shared";

const statusColors:Record<string,string>={Pending:"#f59e0b",Confirmed:"#8b5cf6",Packed:"#06b6d4",Shipped:"#60a5fa",Delivered:"#22c55e",Cancelled:"#ef4444"};

export function AnalyticsPage(){
  const router=useRouter();const {orders,products,formatMoney,toast,addNotification}=useDashboard();const [range,setRange]=useState<AnalyticsRange>(30);const [query,setQuery]=useState("");
  const analytics=useMemo(()=>calculateAnalytics(orders,products,range),[orders,products,range]);const q=query.trim().toLowerCase();const topProducts=analytics.topProducts.filter(item=>!q||item.name.toLowerCase().includes(q));const statuses=analytics.statuses.filter(item=>!q||item.status.toLowerCase().includes(q));const cities=analytics.topCities.filter(item=>!q||item.city.toLowerCase().includes(q));const lowStock=products.filter(product=>product.stock<=10&&(!q||product.name.toLowerCase().includes(q)));
  const changeRange=(next:AnalyticsRange)=>{setRange(next);toast(`Analytics updated to ${next} days`,"info")};
  const exportAnalytics=()=>{if(!analytics.totalOrders&&!analytics.uniqueCustomers&&!analytics.revenue){toast("No data available to export.","error");return}const rows:Array<Array<string|number|boolean>>=[["Selected Period",`${range} Days`],["Total Orders",analytics.totalOrders],["Unique Customers",analytics.uniqueCustomers],["Revenue",analytics.revenue],["Repeat Customers",analytics.repeatCustomers],["",""],["Top Products","Units / Revenue"],...analytics.topProducts.map(item=>[item.name,`${item.units} / ${item.revenue}`]),["",""],["Status Breakdown","Count / Percentage"],...analytics.statuses.map(item=>[item.status,`${item.count} / ${item.percentage}%`]),["",""],["Top Cities","Orders / Revenue"],...analytics.topCities.map(item=>[item.city,`${item.orders} / ${item.revenue}`])];downloadCsv("orderflow-analytics.csv",["Analytics Metric","Value"],rows);toast("CSV exported successfully.");addNotification({title:"CSV export completed",message:`${range}-day analytics were exported.`,type:"Export Completed",actionUrl:"/dashboard/analytics"})};
  return <DashboardShell title="Analytics" searchPlaceholder="Search products, cities, or statuses..." searchValue={query} onSearchChange={setQuery} searchResultsEnabled={false}><div className="analytics-page"><div className="analytics-toolbar"><div className="tabs analytics-range-tabs">{([7,30,90] as AnalyticsRange[]).map(days=><button key={days} className={`tab ${range===days?"active":""}`} onClick={()=>changeRange(days)}>{days} Days</button>)}</div><button className="btn-secondary analytics-export" onClick={exportAnalytics}><Download size={14}/>Export Analytics</button></div>{analytics.totalOrders===0?<EmptyState title="No analytics yet." text="Orders will appear here once customers start submitting orders." action={<button className="btn-primary" onClick={()=>router.push(`${routes.orders}?create=true`)}>Create Test Order</button>}/>:<>
    <div className="stat-grid analytics-stat-grid"><StatCard onClick={()=>router.push(routes.orders)} icon={<ShoppingBag size={16}/>} value={String(analytics.totalOrders)} label="Orders" change={analytics.comparison.orders}/><StatCard onClick={()=>router.push(routes.customers)} icon={<Users size={16}/>} value={String(analytics.uniqueCustomers)} label="Customers" change={analytics.comparison.customers}/><StatCard onClick={()=>router.push(routes.orders)} icon={<BarChart3 size={16}/>} value={formatMoney(analytics.revenue)} label="Revenue" change={analytics.comparison.revenue}/><StatCard onClick={()=>router.push(`${routes.customers}?repeat=true`)} icon={<Repeat2 size={16}/>} value={String(analytics.repeatCustomers)} label="Repeat Customers" change={analytics.comparison.repeat}/></div>
    <div className="analytics-primary-grid"><TrendChart range={range} points={analytics.trend}/><StatusBreakdown statuses={statuses} onStatus={status=>router.push(`${routes.orders}?status=${encodeURIComponent(status)}`)}/></div>
    <div className="analytics-secondary-grid"><TopProducts products={topProducts} formatMoney={formatMoney} onProduct={name=>router.push(`${routes.products}?q=${encodeURIComponent(name)}`)} onAll={()=>router.push(routes.products)}/><SalesSummary analytics={analytics} formatMoney={formatMoney}/></div>
    <div className="analytics-business-grid"><LowStock products={lowStock} onProduct={name=>router.push(`${routes.products}?q=${encodeURIComponent(name)}`)}/><TopCities cities={cities} formatMoney={formatMoney} onCity={city=>router.push(`${routes.orders}?q=${encodeURIComponent(city)}`)}/><CodHealth cod={analytics.cod} onOpen={()=>router.push(`${routes.orders}?q=COD`)}/></div>
    {q&&!topProducts.length&&!cities.length&&!statuses.length&&!lowStock.length&&<div className="analytics-search-empty">No products, cities, or statuses match “{query}”.</div>}
  </>}</div></DashboardShell>;
}

function TrendChart({range,points}:{range:AnalyticsRange;points:ReturnType<typeof calculateAnalytics>["trend"]}){const max=Math.max(1,...points.map(point=>point.orders));const coordinates=points.map((point,index)=>({x:points.length===1?350:index/(points.length-1)*680+10,y:195-point.orders/max*165,...point}));const path=coordinates.map((point,index)=>`${index?"L":"M"}${point.x.toFixed(1)} ${point.y.toFixed(1)}`).join(" ");return <section className="chart card analytics-trend"><div className="analytics-card-head"><div><h3>Orders Trend</h3><p>Order volume across the selected period.</p></div><span>Last {range} days</span></div><svg viewBox="0 0 700 220" role="img" aria-label={`Orders trend for ${range} days`}>{[30,70,110,150,195].map(y=><line key={y} x1="10" x2="690" y1={y} y2={y} stroke="#ececf4"/>)}<defs><linearGradient id="analytics-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4f46e5" stopOpacity=".24"/><stop offset="1" stopColor="#4f46e5" stopOpacity="0"/></linearGradient></defs>{coordinates.length>1&&<path d={`${path} L${coordinates.at(-1)?.x} 205 L${coordinates[0].x} 205Z`} fill="url(#analytics-area)"/>}<path d={path} fill="none" stroke="#3525cd" strokeWidth="4" strokeLinecap="round" strokeLinejoin="round"/>{coordinates.map(point=><g key={`${point.label}-${point.x}`}><circle cx={point.x} cy={point.y} r="5" fill="white" stroke="#3525cd" strokeWidth="3"><title>{point.label}: {point.orders} orders</title></circle></g>)}</svg><div className="trend-labels">{coordinates.map((point,index)=><span key={`${point.label}-${index}`}>{point.label}</span>)}</div></section>}
function StatusBreakdown({statuses,onStatus}:{statuses:ReturnType<typeof calculateAnalytics>["statuses"];onStatus:(status:string)=>void}){const total=statuses.reduce((sum,item)=>sum+item.count,0);let position=0;const segments=statuses.map(item=>{const start=position;position+=item.percentage;return`${statusColors[item.status]} ${start}% ${position}%`}).join(",");return <section className="donut-wrap card analytics-status"><div className="analytics-card-head"><div><h3>Status Breakdown</h3><p>{total} orders by current status.</p></div></div><div className="analytics-donut" style={{background:total?`conic-gradient(${segments})`:"#ececf4"}}><span><b>{total}</b><small>Orders</small></span></div><div className="legend analytics-legend">{statuses.map(item=><button className="legend-row" key={item.status} onClick={()=>onStatus(item.status)}><span className="legend-name"><i className="legend-dot" style={{background:statusColors[item.status]}}/>{item.status}</span><b>{item.count} · {item.percentage}%</b></button>)}</div></section>}
function TopProducts({products,formatMoney,onProduct,onAll}:{products:ReturnType<typeof calculateAnalytics>["topProducts"];formatMoney:(amount:number)=>string;onProduct:(name:string)=>void;onAll:()=>void}){const max=Math.max(1,...products.map(item=>item.units));return <section className="panel card analytics-top-products"><div className="panel-head"><h3>Top Products</h3><button className="text-action" onClick={onAll}>View All Inventory</button></div>{products.length?<div className="best-list">{products.slice(0,5).map((item,index)=><button className="best-item analytics-product-row" key={item.name} onClick={()=>onProduct(item.name)}><div className="best-rank">{index+1}</div><div><b>{item.name}</b><small>{item.units} units sold</small><div className="progress"><span style={{width:`${item.units/max*100}%`}}/></div></div><strong>{formatMoney(item.revenue)}</strong></button>)}</div>:<MiniEmpty text="No matching product sales."/>}</section>}
function SalesSummary({analytics,formatMoney}:{analytics:ReturnType<typeof calculateAnalytics>;formatMoney:(amount:number)=>string}){return <section className="card analytics-summary"><div className="analytics-card-head"><div><h3>Sales Summary</h3><p>Revenue performance for this period.</p></div><TrendingUp size={18}/></div><div className="summary-metrics"><SummaryMetric label="Total Revenue" value={formatMoney(analytics.revenue)}/><SummaryMetric label="Average Order Value" value={formatMoney(analytics.averageOrderValue)}/><SummaryMetric label="Delivered Revenue" value={formatMoney(analytics.deliveredRevenue)} tone="success"/><SummaryMetric label="Pending Revenue" value={formatMoney(analytics.pendingRevenue)} tone="warning"/></div></section>}
function LowStock({products,onProduct}:{products:Product[];onProduct:(name:string)=>void}){return <section className="card analytics-business-card"><div className="analytics-card-head"><div><h3>Low Stock Products</h3><p>Products with 10 or fewer units.</p></div><Boxes size={18}/></div>{products.length?<div className="analytics-compact-list">{products.slice(0,5).map(product=><button key={product.id} onClick={()=>onProduct(product.name)}><span><b>{product.name}</b><small>{product.status}</small></span><strong>{product.stock} left</strong></button>)}</div>:<MiniEmpty text="Stock levels are healthy."/>}</section>}
function TopCities({cities,formatMoney,onCity}:{cities:ReturnType<typeof calculateAnalytics>["topCities"];formatMoney:(amount:number)=>string;onCity:(city:string)=>void}){return <section className="card analytics-business-card"><div className="analytics-card-head"><div><h3>Top Cities</h3><p>Locations ranked by order count.</p></div><MapPin size={18}/></div>{cities.length?<div className="analytics-compact-list">{cities.slice(0,5).map((city,index)=><button key={city.city} onClick={()=>onCity(city.city)}><i>{index+1}</i><span><b>{city.city}</b><small>{formatMoney(city.revenue)}</small></span><strong>{city.orders} orders</strong></button>)}</div>:<MiniEmpty text="No matching city data."/>}</section>}
function CodHealth({cod,onOpen}:{cod:ReturnType<typeof calculateAnalytics>["cod"];onOpen:()=>void}){return <section className="card analytics-business-card cod-health"><div className="analytics-card-head"><div><h3>COD Confirmation Health</h3><p>Confirmation performance for COD orders.</p></div><CheckCircle2 size={18}/></div><div className="cod-rate"><strong>{cod.confirmationRate}%</strong><span>Confirmation rate</span></div><div className="cod-stats"><span><b>{cod.total}</b>Total COD</span><span><b>{cod.confirmed}</b>Confirmed</span><span><b>{cod.cancelled}</b>Cancelled</span></div><button className="btn-secondary" onClick={onOpen}>View COD Orders</button></section>}
function SummaryMetric({label,value,tone=""}:{label:string;value:string;tone?:string}){return <div className={tone}><small>{label}</small><strong>{value}</strong></div>}
function MiniEmpty({text}:{text:string}){return <div className="analytics-mini-empty">{text}</div>}
