import { Eye, Pencil, Trash2 } from "lucide-react";
import { ReactNode } from "react";
import type { Order, OrderStatus } from "@/lib/mock-data";
import { orderStatuses, useDashboard } from "./dashboard-store";

export function StatusBadge({status}:{status:OrderStatus}){return <span className={`status status-${status.toLowerCase()}`}>{status}</span>}
export function StatCard({icon,value,label,change="+12%",onClick}:{icon:ReactNode;value:string;label:string;change?:string;onClick?:()=>void}){const content=<><div className="stat-top"><span className="stat-icon">{icon}</span><span className="trend">{change}</span></div><label>{label}</label><strong>{value}</strong><small>vs. previous period</small></>;return onClick?<button onClick={onClick} className="stat-card card stat-card-button">{content}</button>:<article className="stat-card card">{content}</article>}
export function OrdersTable({orders,onStatus,onView,onEdit,onDelete}:{orders:Order[];onStatus?:(id:string,status:OrderStatus)=>void;onView?:(order:Order)=>void;onEdit?:(order:Order)=>void;onDelete?:(order:Order)=>void}){
  const {formatMoney}=useDashboard();if(!orders.length)return <EmptyState title="No orders found" text="Try changing your search or status filter."/>;
  return <><table className="data-table desktop"><thead><tr><th>Order ID</th><th>Customer</th><th>Product</th><th>Date</th><th>Amount</th><th>Status</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td className="order-id">{o.id}</td><td><b>{o.customer}</b><br/><span className="text-[8px] text-gray-400">{o.phone}</span></td><td>{o.product}</td><td>{o.date}</td><td><b>{formatMoney(o.amount)}</b></td><td>{onStatus?<select aria-label={`Status for ${o.id}`} value={o.status} onChange={e=>onStatus(o.id,e.target.value as OrderStatus)} className={`status status-${o.status.toLowerCase().replaceAll(" ","-")} border-0 outline-0`}>{orderStatuses.map(x=><option key={x}>{x}</option>)}</select>:<StatusBadge status={o.status}/>}</td><td><div className="row-actions">{onView&&<button onClick={()=>onView(o)} aria-label={`View ${o.id}`}><Eye size={13}/><span>View</span></button>}{onEdit&&<button onClick={()=>onEdit(o)} aria-label={`Edit ${o.id}`}><Pencil size={13}/></button>}{onDelete&&<button onClick={()=>onDelete(o)} aria-label={`Delete ${o.id}`} className="danger-action"><Trash2 size={13}/></button>}</div></td></tr>)}</tbody></table><div className="mobile-cards">{orders.map(o=><article className="mobile-order" key={o.id}><div className="mobile-order-top"><span className="order-id">{o.id}</span><StatusBadge status={o.status}/></div><b className="text-xs block mt-3">{o.customer}</b><p>{o.product} · {formatMoney(o.amount)}</p><p>{o.date}</p><div className="mobile-card-actions">{onView&&<button className="btn-secondary" onClick={()=>onView(o)}>View</button>}{onEdit&&<button className="btn-secondary" onClick={()=>onEdit(o)}>Edit</button>}{onDelete&&<button className="btn-danger" onClick={()=>onDelete(o)}>Delete</button>}</div></article>)}</div></>;
}
export function EmptyState({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="empty-state"><strong>{title}</strong><p>{text}</p>{action}</div>}
