import type { Order, OrderStatus, Product } from "./types";

export type AnalyticsRange=7|30|90;
export interface TrendPoint{label:string;orders:number;revenue:number}
export interface ProductAnalytics{name:string;units:number;revenue:number;product?:Product}
export interface StatusAnalytics{status:Exclude<OrderStatus,"Order Received">;count:number;percentage:number}
export interface CityAnalytics{city:string;orders:number;revenue:number}
export interface AnalyticsResult{orders:Order[];previousOrders:Order[];totalOrders:number;uniqueCustomers:number;revenue:number;repeatCustomers:number;averageOrderValue:number;deliveredRevenue:number;pendingRevenue:number;trend:TrendPoint[];topProducts:ProductAnalytics[];statuses:StatusAnalytics[];topCities:CityAnalytics[];cod:{total:number;confirmed:number;cancelled:number;confirmationRate:number};comparison:{orders:string;customers:string;revenue:string;repeat:string}}

const trackedStatuses:StatusAnalytics["status"][]=["Pending","Confirmed","Packed","Shipped","Delivered","Cancelled"];
export function filterOrdersByDateRange(orders:Order[],days:AnalyticsRange,now=new Date()){const end=endOfDay(now),start=new Date(end);start.setDate(start.getDate()-days+1);start.setHours(0,0,0,0);return orders.filter(order=>{const date=orderDate(order);return date>=start&&date<=end})}
export function calculateAnalytics(orders:Order[],products:Product[],days:AnalyticsRange,now=new Date()):AnalyticsResult{
  const current=filterOrdersByDateRange(orders,days,now);const previousEnd=new Date(now);previousEnd.setDate(previousEnd.getDate()-days);const previous=filterOrdersByDateRange(orders,days,previousEnd);const revenue=sum(current);const customerCounts=countBy(current,order=>normalizePhone(order.phone)||order.customer.toLowerCase());const previousCustomers=countBy(previous,order=>normalizePhone(order.phone)||order.customer.toLowerCase());const repeatCustomers=[...customerCounts.values()].filter(count=>count>1).length;const previousRepeats=[...previousCustomers.values()].filter(count=>count>1).length;const statuses=getStatusBreakdown(current);const codOrders=current.filter(order=>order.paymentMethod==="COD"||order.paymentMethod==="Cash on Delivery");const confirmed=codOrders.filter(order=>["Confirmed","Packed","Shipped","Delivered"].includes(order.status)).length;const cancelled=codOrders.filter(order=>order.status==="Cancelled").length;
  return{orders:current,previousOrders:previous,totalOrders:current.length,uniqueCustomers:customerCounts.size,revenue,repeatCustomers,averageOrderValue:current.length?Math.round(revenue/current.length):0,deliveredRevenue:sum(current.filter(order=>order.status==="Delivered")),pendingRevenue:sum(current.filter(order=>["Order Received","Pending","Confirmed","Packed","Shipped"].includes(order.status))),trend:getOrdersTrend(current,days,now),topProducts:getTopProducts(current,products),statuses,topCities:getTopCities(current),cod:{total:codOrders.length,confirmed,cancelled,confirmationRate:codOrders.length?Math.round(confirmed/codOrders.length*100):0},comparison:{orders:compare(current.length,previous.length),customers:compare(customerCounts.size,previousCustomers.size),revenue:compare(revenue,sum(previous)),repeat:compare(repeatCustomers,previousRepeats)}}
}
export function getTopProducts(orders:Order[],products:Product[]){const map=new Map<string,ProductAnalytics>();orders.forEach(order=>{const name=order.productName||order.product,quantity=order.quantity||1;const existing=map.get(name)||{name,units:0,revenue:0,product:products.find(product=>product.id===order.productId||product.name===name)};existing.units+=quantity;existing.revenue+=order.totalAmount||order.amount;map.set(name,existing)});return[...map.values()].sort((a,b)=>b.units-a.units||b.revenue-a.revenue)}
export function getStatusBreakdown(orders:Order[]){const counts=new Map(trackedStatuses.map(status=>[status,0]));orders.forEach(order=>{const status=order.status==="Order Received"?"Pending":order.status;if(counts.has(status as StatusAnalytics["status"]))counts.set(status as StatusAnalytics["status"],(counts.get(status as StatusAnalytics["status"])||0)+1)});return trackedStatuses.map(status=>({status,count:counts.get(status)||0,percentage:orders.length?Math.round((counts.get(status)||0)/orders.length*100):0}))}
export function getTopCities(orders:Order[]){const map=new Map<string,CityAnalytics>();orders.forEach(order=>{const city=order.city?.trim()||"Unknown";const existing=map.get(city)||{city,orders:0,revenue:0};existing.orders+=1;existing.revenue+=order.totalAmount||order.amount;map.set(city,existing)});return[...map.values()].sort((a,b)=>b.orders-a.orders||b.revenue-a.revenue)}
export function getOrdersTrend(orders:Order[],days:AnalyticsRange,now=new Date()){const bucketDays=days===7?1:days===30?3:7,bucketCount=Math.ceil(days/bucketDays),end=endOfDay(now),start=new Date(end);start.setDate(start.getDate()-days+1);start.setHours(0,0,0,0);const points:Array<TrendPoint&{start:Date;end:Date}>=Array.from({length:bucketCount},(_,index)=>{const bucketStart=new Date(start);bucketStart.setDate(bucketStart.getDate()+index*bucketDays);const bucketEnd=new Date(bucketStart);bucketEnd.setDate(bucketEnd.getDate()+bucketDays-1);bucketEnd.setHours(23,59,59,999);return{label:bucketDays===1?bucketStart.toLocaleDateString("en-US",{weekday:"short"}):bucketStart.toLocaleDateString("en-US",{month:"short",day:"numeric"}),orders:0,revenue:0,start:bucketStart,end:bucketEnd}});orders.forEach(order=>{const date=orderDate(order),point=points.find(item=>date>=item.start&&date<=item.end);if(point){point.orders+=1;point.revenue+=order.totalAmount||order.amount}});return points.map(({label,orders:count,revenue})=>({label,orders:count,revenue}))}
function compare(current:number,previous:number){if(current===previous)return"Stable";if(previous===0)return current>0?"+100%":"Stable";const value=Math.round((current-previous)/previous*1000)/10;return`${value>0?"+":""}${value}%`}
function orderDate(order:Order){const parsed=new Date(order.createdAt||order.date);return Number.isNaN(parsed.getTime())?new Date(0):parsed}
function endOfDay(value:Date){const result=new Date(value);result.setHours(23,59,59,999);return result}
function sum(orders:Order[]){return orders.reduce((total,order)=>total+(order.totalAmount||order.amount),0)}
function countBy<T>(items:T[],key:(item:T)=>string){const map=new Map<string,number>();items.forEach(item=>{const value=key(item);map.set(value,(map.get(value)||0)+1)});return map}
function normalizePhone(value:string){return value.replace(/\D/g,"")}
