import type { Activity, CheckoutConfig, Customer, Order, Product } from "./types";
export type { Activity, AnalyticsMetric, CountryCode, CurrencyCode, Customer, CustomerOrderHistory, Notification, NotificationType, Order, OrderStatus, OrderTimelineItem, PaymentMethod, Product, ProductCategory, ProductCustomField, ProductCustomFieldType, ProductStatus, ProductVariant, StoreSettings } from "./types";

export const orders: Order[] = [
  { id:"ORD-1042",customer:"Ali Hassan",initials:"AH",phone:"+92 300 1234567",product:"Premium Hoodie",variant:"Black · Large",quantity:1,date:"Jun 22, 2026",amount:4500,status:"Shipped",address:"House 18, Street 7, Gulberg III",city:"Lahore",paymentMethod:"COD",notes:"Call before delivery.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 22, 09:12 AM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 22, 09:35 AM"},{status:"Packed",label:"Packed",timestamp:"Jun 22, 11:20 AM"},{status:"Shipped",label:"Shipped",timestamp:"Jun 22, 02:10 PM"}] },
  { id:"ORD-1043",customer:"Sara Khan",initials:"SK",phone:"+92 321 9876543",product:"Linen Co-ord Set",variant:"Sand · Medium",quantity:2,date:"Jun 22, 2026",amount:25998,status:"Pending",address:"House 112, S-14, Gulberg III",city:"Lahore",paymentMethod:"JazzCash",notes:"Gift wrap both sets.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 22, 10:05 AM"}] },
  { id:"ORD-1044",customer:"Hamza Malik",initials:"HM",phone:"+92 345 5556727",product:"Leather Wallet",variant:"Brown",quantity:1,date:"Jun 21, 2026",amount:8250,status:"Delivered",address:"DHA Phase 5",city:"Karachi",paymentMethod:"Bank Transfer",notes:"Payment verified.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 21, 08:20 AM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 21, 08:44 AM"},{status:"Packed",label:"Packed",timestamp:"Jun 21, 10:15 AM"},{status:"Shipped",label:"Shipped",timestamp:"Jun 21, 12:30 PM"},{status:"Delivered",label:"Delivered",timestamp:"Jun 22, 04:10 PM"}] },
  { id:"ORD-1045",customer:"Ayesha Noor",initials:"AN",phone:"+92 312 4443322",product:"Summer Kurti",variant:"Blue · Small",quantity:1,date:"Jun 20, 2026",amount:7400,status:"Confirmed",address:"Street 8, F-7/2",city:"Islamabad",paymentMethod:"Easypaisa",notes:"Deliver after 5 PM.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 20, 01:15 PM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 20, 01:40 PM"}] },
  { id:"ORD-1046",customer:"Bilal Ahmed",initials:"BA",phone:"+92 333 9081726",product:"Classic Sneakers",variant:"White · EU 43",quantity:1,date:"Jun 19, 2026",amount:5100,status:"Packed",address:"Block H, Johar Town",city:"Lahore",paymentMethod:"COD",notes:"",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 19, 11:00 AM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 19, 11:20 AM"},{status:"Packed",label:"Packed",timestamp:"Jun 20, 09:10 AM"}] },
  { id:"ORD-1047",customer:"Hira Iqbal",initials:"HI",phone:"+92 301 7654321",product:"Silk Scarf",variant:"Emerald",quantity:3,date:"Jun 18, 2026",amount:9600,status:"Cancelled",address:"Satellite Town",city:"Rawalpindi",paymentMethod:"JazzCash",notes:"Customer requested cancellation.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 18, 03:10 PM"},{status:"Cancelled",label:"Cancelled",timestamp:"Jun 18, 04:05 PM"}] },
  { id:"ORD-1048",customer:"Usman Raza",initials:"UR",phone:"+92 322 1122334",product:"Minimal Desk Lamp",variant:"Matte Black",quantity:1,date:"Jun 16, 2026",amount:6800,status:"Shipped",address:"Model Town Extension",city:"Lahore",paymentMethod:"Bank Transfer",notes:"Office reception delivery.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 16, 09:00 AM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 16, 09:25 AM"},{status:"Packed",label:"Packed",timestamp:"Jun 16, 01:10 PM"},{status:"Shipped",label:"Shipped",timestamp:"Jun 17, 08:30 AM"}] },
  { id:"ORD-1049",customer:"Mariam Faisal",initials:"MF",phone:"+92 304 5566778",product:"Pearl Earrings",variant:"Gold",quantity:2,date:"Jun 12, 2026",amount:11800,status:"Delivered",address:"Clifton Block 5",city:"Karachi",paymentMethod:"COD",notes:"",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 12, 02:00 PM"},{status:"Confirmed",label:"Confirmed",timestamp:"Jun 12, 02:20 PM"},{status:"Packed",label:"Packed",timestamp:"Jun 13, 10:05 AM"},{status:"Shipped",label:"Shipped",timestamp:"Jun 13, 04:30 PM"},{status:"Delivered",label:"Delivered",timestamp:"Jun 15, 12:15 PM"}] },
  { id:"ORD-1050",customer:"Danish Khan",initials:"DK",phone:"+92 331 6677889",product:"Canvas Backpack",variant:"Olive",quantity:1,date:"Jun 5, 2026",amount:5900,status:"Pending",address:"University Road",city:"Peshawar",paymentMethod:"Easypaisa",notes:"Student discount applied.",timeline:[{status:"Received",label:"Order Received",timestamp:"Jun 5, 06:45 PM"}] },
  { id:"ORD-1051",customer:"Nida Aslam",initials:"NA",phone:"+92 315 7788990",product:"Ceramic Vase",variant:"Ivory · Large",quantity:2,date:"May 28, 2026",amount:14400,status:"Delivered",address:"Bahria Town Phase 4",city:"Rawalpindi",paymentMethod:"Bank Transfer",notes:"Fragile item.",timeline:[{status:"Received",label:"Order Received",timestamp:"May 28, 10:00 AM"},{status:"Confirmed",label:"Confirmed",timestamp:"May 28, 10:35 AM"},{status:"Packed",label:"Packed",timestamp:"May 29, 09:15 AM"},{status:"Shipped",label:"Shipped",timestamp:"May 29, 03:00 PM"},{status:"Delivered",label:"Delivered",timestamp:"May 31, 01:40 PM"}] },
  { id:"ORD-1052",customer:"Omer Farooq",initials:"OF",phone:"+92 343 8899001",product:"Smart Watch Strap",variant:"Navy · 44mm",quantity:2,date:"May 18, 2026",amount:4200,status:"Packed",address:"Cantt Area",city:"Multan",paymentMethod:"COD",notes:"",timeline:[{status:"Received",label:"Order Received",timestamp:"May 18, 12:30 PM"},{status:"Confirmed",label:"Confirmed",timestamp:"May 18, 01:00 PM"},{status:"Packed",label:"Packed",timestamp:"May 19, 11:20 AM"}] },
  { id:"ORD-1053",customer:"Zoya Siddiqui",initials:"ZS",phone:"+92 306 9900112",product:"Premium Abaya",variant:"Black · 56",quantity:1,date:"Apr 30, 2026",amount:15750,status:"Confirmed",address:"PECHS Block 2",city:"Karachi",paymentMethod:"JazzCash",notes:"Include matching scarf.",timeline:[{status:"Received",label:"Order Received",timestamp:"Apr 30, 05:20 PM"},{status:"Confirmed",label:"Confirmed",timestamp:"Apr 30, 05:50 PM"}] },
];

export const products: Product[] = [
  {id:1,name:"Summer Kurti",category:"Women",price:7400,image:"/images/orderflow/stitch-01.png",status:"Active",ordersCount:164,stock:32,description:"Lightweight printed summer kurti with breathable cotton fabric.",sizes:["S","M","L"],colors:["Blue","Rose"],variants:[{label:"Size",values:["S","M","L"]},{label:"Color",values:["Blue","Rose"]}],customFields:[],createdAt:"May 2, 2026",updatedAt:"Jun 20, 2026"},
  {id:2,name:"Leather Wallet",category:"Accessories",price:8250,image:"/images/orderflow/stitch-02.png",status:"Active",ordersCount:196,stock:18,description:"Hand-finished leather wallet with six card slots and a slim profile.",sizes:[],colors:["Brown","Black"],variants:[{label:"Color",values:["Brown","Black"]}],customFields:[],createdAt:"Apr 15, 2026",updatedAt:"Jun 18, 2026"},
  {id:3,name:"Linen Co-ord Set",category:"Women",price:12999,image:"/images/orderflow/stitch-03.png",status:"Active",ordersCount:312,stock:24,description:"Premium linen matching set designed for effortless everyday styling.",sizes:["S","M","L","XL"],colors:["Sand","Black"],variants:[{label:"Size",values:["S","M","L","XL"]},{label:"Color",values:["Sand","Black"]}],customFields:[],createdAt:"Mar 22, 2026",updatedAt:"Jun 22, 2026"},
  {id:4,name:"Premium Hoodie",category:"Apparel",price:4500,image:"/images/orderflow/stitch-04.png",status:"Active",ordersCount:428,stock:11,description:"Heavyweight fleece hoodie with a relaxed fit and reinforced seams.",sizes:["S","M","L","XL"],colors:["Black","Grey","Navy"],variants:[{label:"Size",values:["S","M","L","XL"]},{label:"Color",values:["Black","Grey","Navy"]}],customFields:[],createdAt:"Feb 10, 2026",updatedAt:"Jun 21, 2026"},
  {id:5,name:"Sneakers",category:"Footwear",price:5100,image:"/images/orderflow/stitch-05.png",status:"Draft",ordersCount:88,stock:40,description:"Comfort-focused everyday sneakers with a flexible cushioned sole.",sizes:["39","40","41","42","43"],colors:["White","Black"],variants:[{label:"Size",values:["39","40","41","42","43"]},{label:"Color",values:["White","Black"]}],customFields:[],createdAt:"Jun 12, 2026",updatedAt:"Jun 19, 2026"},
  {id:6,name:"Printed T-Shirt",category:"Apparel",price:2800,image:"/images/orderflow/stitch-06.png",status:"Active",ordersCount:143,stock:56,description:"Soft combed-cotton t-shirt featuring an original minimal print.",sizes:["S","M","L","XL"],colors:["White","Olive"],variants:[{label:"Size",values:["S","M","L","XL"]},{label:"Color",values:["White","Olive"]}],customFields:[],createdAt:"May 18, 2026",updatedAt:"Jun 17, 2026"},
  {id:7,name:"Abaya Set",category:"Women",price:15750,image:"/images/orderflow/stitch-07.png",status:"Active",ordersCount:97,stock:15,description:"Flowing premium abaya supplied with a coordinated lightweight scarf.",sizes:["52","54","56","58"],colors:["Black","Mocha"],variants:[{label:"Size",values:["52","54","56","58"]},{label:"Color",values:["Black","Mocha"]}],customFields:[],createdAt:"Apr 4, 2026",updatedAt:"Jun 16, 2026"},
  {id:8,name:"Structured Handbag",category:"Accessories",price:9800,image:"/images/orderflow/stitch-01.png",status:"Draft",ordersCount:52,stock:20,description:"Structured vegan-leather handbag with removable shoulder strap.",sizes:[],colors:["Tan","Black","Burgundy"],variants:[{label:"Color",values:["Tan","Black","Burgundy"]}],customFields:[],createdAt:"Jun 8, 2026",updatedAt:"Jun 15, 2026"},
  {id:9,name:"Smart Watch",category:"Electronics",price:18500,image:"/images/orderflow/stitch-02.png",status:"Active",ordersCount:225,stock:9,description:"Feature-rich smart watch with fitness tracking and call notifications.",sizes:["42mm","46mm"],colors:["Midnight","Silver"],variants:[{label:"Size",values:["42mm","46mm"]},{label:"Color",values:["Midnight","Silver"]}],customFields:[],createdAt:"Jan 26, 2026",updatedAt:"Jun 22, 2026"},
  {id:10,name:"Signature Perfume",category:"Beauty",price:6900,image:"/images/orderflow/stitch-03.png",status:"Archived",ordersCount:76,stock:0,description:"Warm floral fragrance with amber, jasmine and sandalwood notes.",sizes:["50ml","100ml"],colors:[],variants:[{label:"Size",values:["50ml","100ml"]}],customFields:[{id:"fragrance-type",name:"Fragrance Type",type:"Dropdown",options:["Oud","Rose","Musk"]}],createdAt:"Dec 10, 2025",updatedAt:"May 30, 2026"},
  {id:11,name:"Classic Sunglasses",category:"Accessories",price:4200,image:"/images/orderflow/stitch-04.png",status:"Active",ordersCount:181,stock:27,description:"UV400 polarized sunglasses with a timeless lightweight frame.",sizes:[],colors:["Black","Tortoise"],variants:[{label:"Color",values:["Black","Tortoise"]}],customFields:[],createdAt:"Mar 8, 2026",updatedAt:"Jun 14, 2026"},
  {id:12,name:"Denim Jacket",category:"Apparel",price:8900,image:"/images/orderflow/stitch-05.png",status:"Draft",ordersCount:41,stock:35,description:"Mid-weight denim jacket with a relaxed cut and vintage wash.",sizes:["S","M","L","XL"],colors:["Indigo","Washed Black"],variants:[{label:"Size",values:["S","M","L","XL"]},{label:"Color",values:["Indigo","Washed Black"]}],customFields:[],createdAt:"Jun 20, 2026",updatedAt:"Jun 21, 2026"},
];

export const defaultCheckoutConfig:CheckoutConfig={storeId:"store-id",storeName:"Lumina Studio",logo:"",brandColor:"#3525CD",buttonColor:"#0060AC",selectedProductId:1,optionalFields:{email:true,referral:false,giftNote:false},customFields:[],codEnabled:true,requirePhone:true,requireAddress:true,requireCity:true,allowMultipleProducts:false,trackingEnabled:true,thankYouMessage:"Your order has been sent to the seller. You can track it anytime using your phone number.",defaultOrderStatus:"Order Received",updatedAt:""};

export const customers: Customer[] = [
  {id:1,name:"Ali Hassan",initials:"AH",email:"ali.hassan@email.com",phone:"+92 300 1234567",country:"Pakistan",city:"Lahore",address:"House 18, Gulberg III",ordersCount:12,totalSpent:45900,avgTicket:3825,isRepeatCustomer:true,createdAt:"Jan 12, 2025",notes:"Prefers evening delivery.",orderHistory:[{id:"ORD-1042",date:"Jun 22, 2026",products:"Premium Hoodie",amount:4500,status:"Shipped"}]},
  {id:2,name:"Sara Khan",initials:"SK",email:"sara.khan@email.com",phone:"+92 321 9876543",country:"Pakistan",city:"Lahore",address:"House 112, S-14, Gulberg III",ordersCount:48,totalSpent:182400,avgTicket:3800,isRepeatCustomer:true,createdAt:"Jan 2, 2022",notes:"High-value customer. Gift wraps frequently.",orderHistory:[{id:"ORD-1043",date:"Jun 22, 2026",products:"2 × Linen Co-ord Set",amount:25998,status:"Pending"},{id:"ORD-1038",date:"May 30, 2026",products:"Summer Kurti",amount:7400,status:"Delivered"}]},
  {id:3,name:"Hamza Malik",initials:"HM",email:"hamza.malik@email.com",phone:"+92 345 5556727",country:"Pakistan",city:"Karachi",address:"DHA Phase 5",ordersCount:3,totalSpent:19200,avgTicket:6400,isRepeatCustomer:false,createdAt:"Mar 18, 2026",notes:"Bank transfer verified.",orderHistory:[{id:"ORD-1044",date:"Jun 21, 2026",products:"Leather Wallet",amount:8250,status:"Delivered"}]},
  {id:4,name:"Ayesha Noor",initials:"AN",email:"ayesha.noor@email.com",phone:"+92 312 4443322",country:"Pakistan",city:"Islamabad",address:"Street 8, F-7/2",ordersCount:21,totalSpent:83000,avgTicket:3952,isRepeatCustomer:true,createdAt:"Aug 7, 2024",notes:"Deliver after 5 PM.",orderHistory:[{id:"ORD-1045",date:"Jun 20, 2026",products:"Summer Kurti",amount:7400,status:"Confirmed"}]},
  {id:5,name:"Priya Sharma",initials:"PS",email:"priya.sharma@email.com",phone:"+91 98765 43210",country:"India",city:"Delhi",address:"Saket, New Delhi",ordersCount:9,totalSpent:67400,avgTicket:7489,isRepeatCustomer:true,createdAt:"Nov 14, 2025",notes:"Interested in new apparel launches.",orderHistory:[{id:"ORD-1036",date:"Jun 10, 2026",products:"Abaya Set",amount:15750,status:"Delivered"}]},
  {id:6,name:"Arjun Mehta",initials:"AM",email:"arjun.mehta@email.com",phone:"+91 99887 76655",country:"India",city:"Mumbai",address:"Bandra West, Mumbai",ordersCount:2,totalSpent:12700,avgTicket:6350,isRepeatCustomer:false,createdAt:"May 4, 2026",notes:"",orderHistory:[{id:"ORD-1035",date:"Jun 8, 2026",products:"Sneakers",amount:5100,status:"Shipped"}]},
  {id:7,name:"Siti Rahma",initials:"SR",email:"siti.rahma@email.com",phone:"+62 812-3456-7890",country:"Indonesia",city:"Jakarta",address:"Kebayoran Baru, Jakarta",ordersCount:15,totalSpent:94300,avgTicket:6287,isRepeatCustomer:true,createdAt:"Jun 20, 2024",notes:"Prefers WhatsApp updates.",orderHistory:[{id:"ORD-1034",date:"Jun 6, 2026",products:"Structured Handbag",amount:9800,status:"Delivered"}]},
  {id:8,name:"Budi Santoso",initials:"BS",email:"budi.santoso@email.com",phone:"+62 811-2233-4455",country:"Indonesia",city:"Bandung",address:"Dago, Bandung",ordersCount:4,totalSpent:31200,avgTicket:7800,isRepeatCustomer:false,createdAt:"Feb 12, 2026",notes:"",orderHistory:[{id:"ORD-1033",date:"Jun 4, 2026",products:"Smart Watch",amount:18500,status:"Delivered"}]},
  {id:9,name:"Ana Oliveira",initials:"AO",email:"ana.oliveira@email.com",phone:"+55 11 99876-5432",country:"Brazil",city:"São Paulo",address:"Jardins, São Paulo",ordersCount:18,totalSpent:128900,avgTicket:7161,isRepeatCustomer:true,createdAt:"Sep 9, 2024",notes:"VIP customer.",orderHistory:[{id:"ORD-1032",date:"Jun 2, 2026",products:"Linen Co-ord Set",amount:12999,status:"Delivered"}]},
  {id:10,name:"Lucas Silva",initials:"LS",email:"lucas.silva@email.com",phone:"+55 21 98765-1234",country:"Brazil",city:"Rio de Janeiro",address:"Copacabana, Rio de Janeiro",ordersCount:1,totalSpent:4500,avgTicket:4500,isRepeatCustomer:false,createdAt:"Jun 1, 2026",notes:"First international order.",orderHistory:[{id:"ORD-1031",date:"Jun 1, 2026",products:"Premium Hoodie",amount:4500,status:"Delivered"}]},
  {id:11,name:"Emily Carter",initials:"EC",email:"emily.carter@email.com",phone:"+1 415 555 0198",country:"United States",city:"San Francisco",address:"Mission District, San Francisco",ordersCount:7,totalSpent:51600,avgTicket:7371,isRepeatCustomer:true,createdAt:"Oct 22, 2025",notes:"Email receipts only.",orderHistory:[{id:"ORD-1030",date:"May 28, 2026",products:"Denim Jacket",amount:8900,status:"Delivered"}]},
  {id:12,name:"Noah Williams",initials:"NW",email:"noah.williams@email.com",phone:"+1 212 555 0144",country:"United States",city:"New York",address:"Brooklyn, New York",ordersCount:3,totalSpent:22900,avgTicket:7633,isRepeatCustomer:false,createdAt:"Jan 16, 2026",notes:"",orderHistory:[{id:"ORD-1029",date:"May 24, 2026",products:"Classic Sunglasses",amount:4200,status:"Delivered"}]},
  {id:13,name:"Olivia Brown",initials:"OB",email:"olivia.brown@email.com",phone:"+44 7700 900123",country:"United Kingdom",city:"London",address:"Shoreditch, London",ordersCount:11,totalSpent:89700,avgTicket:8155,isRepeatCustomer:true,createdAt:"Jul 13, 2024",notes:"Often orders gifts.",orderHistory:[{id:"ORD-1028",date:"May 20, 2026",products:"Signature Perfume",amount:6900,status:"Delivered"}]},
  {id:14,name:"James Wilson",initials:"JW",email:"james.wilson@email.com",phone:"+44 7700 900456",country:"United Kingdom",city:"Manchester",address:"Northern Quarter, Manchester",ordersCount:5,totalSpent:33600,avgTicket:6720,isRepeatCustomer:true,createdAt:"Dec 3, 2025",notes:"",orderHistory:[{id:"ORD-1027",date:"May 16, 2026",products:"Printed T-Shirt",amount:2800,status:"Delivered"}]},
  {id:15,name:"Maya Putri",initials:"MP",email:"maya.putri@email.com",phone:"+62 813-9988-7766",country:"Indonesia",city:"Surabaya",address:"Tegalsari, Surabaya",ordersCount:6,totalSpent:42100,avgTicket:7017,isRepeatCustomer:true,createdAt:"Feb 22, 2025",notes:"Prefers eco-friendly packaging.",orderHistory:[{id:"ORD-1026",date:"May 12, 2026",products:"Structured Handbag",amount:9800,status:"Delivered"}]},
];

export const activities: Activity[] = [
  { title: "New Order #1047", detail: "Sara Khan purchased Linen Co-ord Set", time: "2 minutes ago", tone: "primary" },
  { title: "Status Updated", detail: "Order #1042 marked as Delivered", time: "45 minutes ago", tone: "success" },
  { title: "Stock Alert", detail: "Premium Hoodie is low on stock", time: "2 hours ago", tone: "warning" },
  { title: "Settings Modified", detail: "Checkout page branding updated", time: "5 hours ago", tone: "muted" },
];

export const formatPKR = (amount: number) => `PKR ${amount.toLocaleString("en-PK")}`;
